### ISSUE TITLE
Problem with Lightbox button style

### ISSUE THREAD

**Issue by MariuszMilka** [goaround/gallery-block-lightbox#15]
Great plugin. However, on my sites I have global style settings set for Elementor and Wordpress to work well together and your lightbox seems to take some of the color settings from these global settings. Can you please add some basic options to configure next, previous and close buttons foreground and background colors?

**Comment by goaround** [comment]
Hi @MariuszMilka,

I think that this could be done with CSS pretty easy. See https://github.com/feimosi/baguetteBox.js/blob/3d5c0485441832c2e6f803500b6950db5e269678/src/baguetteBox.scss#L105

**Comment by MariuszMilka** [comment]
I am making a website for a client. If I change anything in the CSS file and there is an update in 6 months, my client will email me that all colors suddenly changed. That is why I was asking about more clien-proof solution

**Comment by goaround** [comment]
Typically, you override the CSS in a separate CSS file. Like from the (child) theme. See: https://css-tricks.com/methods-overriding-styles-wordpress/
