### ISSUE TITLE
Suggestion: don't wait for `load` event

### ISSUE THREAD

**Issue by stokesman** [goaround/gallery-block-lightbox#8]
The gallery I used this on has many large images that can (especially depending on the connection) delay the `load` event well beyond time to interactive. That makes it likely that clicking an image will navigate to it directly instead of the desired (scripted) behavior.

I noticed that the baguetteBox readme says:
>Note: if you import baguetteBox using the <script> tag, remember to run it after the document has loaded:

That's probably just the simplified general recommendation. I modified this plugin to execute `baguetteBox.run` immediately and it works well.

Thanks for this straightforward plugin!

**Comment by goaround** [comment]
Unfortunately, if the script is loaded `async` or even with `defer`, there is no guarantee, that `baguetteBox.run` is available. A lot of performance optimization plugins applies the `async` or `defer` attribute to scripts. For this reason, I cannot change the behavior.

**Comment by stokesman** [comment]
I understand. I would think adding a hook that enables this behavior might be something to consider but no worries if you think there's not enough demand. Thanks again!
