### ISSUE TITLE
change svg arrows in lightbox

### ISSUE THREAD

**Issue by nikolailehbrink** [goaround/gallery-block-lightbox#9]
Hi Johannes,
Ich würde gerne die svgs der Pfeile und des Schließen-Icons anpassen, gibt es da eine Möglichkeit oder wie sollte ich am besten vorgehen?

**Comment by goaround** [comment]
Hi @nikolailehbrink,

das Plugin nutzt ja einfach nur baguetteBox.js. Da gibt es so direkt keine Option. Wenn müsstest du baguetteBox.js forken, das SVG hier anpassen: https://github.com/feimosi/baguetteBox.js/blob/dev/src/baguetteBox.js und dann selber das JavaScript kompilieren.

**Comment by nikolailehbrink** [comment]
Alles klar @goaround! Danke dir!
